"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const jsx_runtime_1 = require("react/jsx-runtime");
const lucide_react_1 = require("lucide-react");
const card_1 = require("@/components/ui/card");
const button_1 = require("@/components/ui/button");
const PrivacyNotice = ({ onBack }) => {
    return ((0, jsx_runtime_1.jsxs)("div", { className: "container mx-auto p-4 space-y-6", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex items-center justify-between", children: [(0, jsx_runtime_1.jsxs)(button_1.Button, { onClick: onBack, variant: "outline", className: "flex items-center gap-2", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.ArrowLeft, { className: "h-4 w-4" }), "Back to Dashboard"] }), (0, jsx_runtime_1.jsx)("h1", { className: "text-2xl font-bold", children: "Privacy Notice" }), (0, jsx_runtime_1.jsx)("div", { className: "w-20" }), " "] }), (0, jsx_runtime_1.jsxs)(card_1.Card, { className: "p-6 border-green-200 bg-green-50", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex items-center space-x-3 mb-4", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Shield, { className: "h-6 w-6 text-green-600" }), (0, jsx_runtime_1.jsx)("h3", { className: "text-lg font-semibold text-green-800", children: "Privacy & Security Guaranteed" })] }), (0, jsx_runtime_1.jsxs)("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-4 text-sm", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex items-start space-x-2", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Database, { className: "h-4 w-4 text-green-600 mt-0.5 flex-shrink-0" }), (0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)("p", { className: "font-medium text-green-800", children: "Local Storage Only" }), (0, jsx_runtime_1.jsx)("p", { className: "text-green-700", children: "All data stays on your device" })] })] }), (0, jsx_runtime_1.jsxs)("div", { className: "flex items-start space-x-2", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Lock, { className: "h-4 w-4 text-green-600 mt-0.5 flex-shrink-0" }), (0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)("p", { className: "font-medium text-green-800", children: "No Internet Required" }), (0, jsx_runtime_1.jsx)("p", { className: "text-green-700", children: "Works completely offline" })] })] }), (0, jsx_runtime_1.jsxs)("div", { className: "flex items-start space-x-2", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Eye, { className: "h-4 w-4 text-green-600 mt-0.5 flex-shrink-0" }), (0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)("p", { className: "font-medium text-green-800", children: "Zero Data Sharing" }), (0, jsx_runtime_1.jsx)("p", { className: "text-green-700", children: "No external servers accessed" })] })] })] }), (0, jsx_runtime_1.jsx)("div", { className: "mt-4 p-3 bg-green-100 rounded-lg", children: (0, jsx_runtime_1.jsx)("p", { className: "text-xs text-green-800 font-medium", children: "\uD83D\uDD12 Your privacy is our top priority. This app operates entirely offline and never transmits your personal data." }) })] })] }));
};
exports.default = PrivacyNotice;
